In [ ]:
!pip install numpy


In [3]:
import numpy as np

# 1D Array
array_1d = np.array([1, 2, 3, 4, 5])  # Create a 1D array
print("1D Array:", array_1d)

# 2D Array (Matrix)
array_2d = np.array([[1, 2, 3], [4, 5, 6]])  # Create a 2D array (matrix)
print("2D Array:\n", array_2d)

# Create an array of zeros
zeros_array = np.zeros((3, 3))  # 3x3 matrix filled with zeros
print("Zeros Array:\n", zeros_array)

# Create an array of ones
ones_array = np.ones((2, 3))  # 2x3 matrix filled with ones
print("Ones Array:\n", ones_array)

# Create a range of numbers
range_array = np.arange(0, 10, 2)  # Create an array from 0 to 10, with step 2
print("Range Array:", range_array)


1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Range Array: [0 2 4 6 8]


In [4]:
# Element-wise addition
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
sum_array = array_a + array_b  # Add corresponding elements of two arrays
print("Sum of Arrays:", sum_array)

# Element-wise multiplication
mult_array = array_a * array_b  # Multiply corresponding elements
print("Multiplication of Arrays:", mult_array)

# Dot product (Matrix Multiplication)
dot_product = np.dot(array_a, array_b)  # Compute the dot product
print("Dot Product:", dot_product)


Sum of Arrays: [5 7 9]
Multiplication of Arrays: [ 4 10 18]
Dot Product: 32


In [ ]:
# Slicing a 1D array
print("First element:", array_1d[0])  # Access the first element
print("Last element:", array_1d[-1])  # Access the last element
print("Elements from index 1 to 3:", array_1d[1:4])  # Slice the array (index 1 to 3)

# Slicing a 2D array
print("First row:", array_2d[0, :])  # Access the first row
print("First column:", array_2d[:, 0])  # Access the first column
print("Element at row 1, column 2:", array_2d[1, 2])  # Access specific element (row 1, column 2)
